services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    ports:
      - "${PORT}:8080"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data"
